# Generated by Django 3.0.8 on 2020-07-28 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume_app', '0002_auto_20200728_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personals', to=settings.AUTH_USER_MODEL),
        ),
    ]
