# Generated by Django 3.0.8 on 2020-07-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0003_auto_20200728_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='user',
            new_name='student',
        ),
    ]
