# Generated by Django 3.0.8 on 2020-07-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0007_auto_20200729_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='field',
            new_name='stream',
        ),
        migrations.AlterField(
            model_name='education',
            name='percentage_or_cg',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
