# Generated by Django 3.0.8 on 2020-07-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0009_auto_20200729_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='stream',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
