# Generated by Django 3.0.8 on 2020-07-29 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0010_auto_20200729_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='school_name',
            new_name='institution_name',
        ),
    ]
