# Generated by Django 3.0.8 on 2020-07-29 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume_app', '0011_auto_20200729_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=150)),
                ('job_title', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('start_month', models.CharField(choices=[('jan', 'JAN'), ('feb', 'FEB'), ('march', 'MARCH'), ('april', 'APRIL'), ('may', 'MAY'), ('june', 'JUNE'), ('july', 'JULY'), ('aug', 'AUG'), ('sep', 'SEP'), ('oct', 'OCT'), ('nov', 'NOV'), ('dec', 'DEC')], default='may', max_length=6)),
                ('start_year', models.CharField(choices=[('2009', '2009'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2018', '2017'), ('2019', '2019'), ('2020', '2020')], default='2019', max_length=6)),
                ('presently_working', models.BooleanField()),
                ('end_month', models.CharField(blank=True, choices=[('jan', 'JAN'), ('feb', 'FEB'), ('march', 'MARCH'), ('april', 'APRIL'), ('may', 'MAY'), ('june', 'JUNE'), ('july', 'JULY'), ('aug', 'AUG'), ('sep', 'SEP'), ('oct', 'OCT'), ('nov', 'NOV'), ('dec', 'DEC')], max_length=6, null=True)),
                ('end_year', models.CharField(blank=True, choices=[('2009', '2009'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2018', '2017'), ('2019', '2019'), ('2020', '2020')], max_length=6, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
