# Generated by Django 3.0.8 on 2020-07-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0012_employment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
