# Generated by Django 3.0.8 on 2020-07-29 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0015_auto_20200729_1132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
