# Generated by Django 3.0.8 on 2020-07-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0020_certificate_certificate_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_code_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='month',
            field=models.CharField(choices=[('JAN', '1'), ('FEB', '2'), ('MARCH', '3'), ('APRIL', '4'), ('MAY', '5'), ('JUNE', '6'), ('JULY', '7'), ('AUG', '8'), ('SEP', '9'), ('OCT', '10'), ('NOV', '11'), ('DEC', '12')], default='MAY', max_length=6),
        ),
        migrations.AlterField(
            model_name='employment',
            name='end_month',
            field=models.CharField(blank=True, choices=[('JAN', '1'), ('FEB', '2'), ('MARCH', '3'), ('APRIL', '4'), ('MAY', '5'), ('JUNE', '6'), ('JULY', '7'), ('AUG', '8'), ('SEP', '9'), ('OCT', '10'), ('NOV', '11'), ('DEC', '12')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='start_month',
            field=models.CharField(choices=[('JAN', '1'), ('FEB', '2'), ('MARCH', '3'), ('APRIL', '4'), ('MAY', '5'), ('JUNE', '6'), ('JULY', '7'), ('AUG', '8'), ('SEP', '9'), ('OCT', '10'), ('NOV', '11'), ('DEC', '12')], default='MAY', max_length=6),
        ),
    ]
